export const API_CONFIG = {
  baseURL: process.env.NEXT_PUBLIC_API_URL || "http://localhost:8080",
  timeout: 30000,
} as const;

export const API_ENDPOINTS = {
  currency: "/api/currency",
  employment: "/api/employment",
  experience: "/api/experience",
  workFormat: "/api/format",
  languages: "/api/languages",
  vacancies: "/api/vacancies",
  vacancyFilters: "/api/vacancies/filters",
  vacancyDirections: "/api/vacancies/directions",
  citySuggestions: "/api/cities/suggestions",
  tasks: "/api/tasks",
  questions: "/api/questions",
  skills: "/api/skill",
  login: "/api/auth/login",
  refreshToken: "/api/auth/update-refresh-token",
  logout: "/api/auth/logout",
  me: "/api/auth/me",
  register: "/api/auth/register",
  verifyEmail: "/api/auth/email/verify",
  resendEmailVerification: "/api/auth/email/verification/resend",
  changeEmail: "/api/auth/email/change",
  forgotPassword: "/api/auth/password/forgot",
  resetPassword: "/api/auth/password/reset",
  userVacanciesFavorite: "/api/vacancies/favorites",
  userFavoriteVacancies: "/api/users/me/favorite-vacancies",
  userProfile: "/api/users/me/profile",
  userProfilePhoto: "/api/users/me/profile/photo",
  userResumes: "/api/users/me/resumes",
  userApplicationsHistory: "/api/users/me/applications/history",
  employerProfile: "/api/employer/me/profile",
  employerProfilePhoto: "/api/employer/me/profile/photo",
  employerVacancies: "/api/employer/me/vacancies",
  employerApplications: "/api/employer/me/applications",
  employerCandidates: "/api/employer/me/candidates",
  moderationVacancies: "/api/moderation/vacancies",
  moderationUsers: "/api/moderation/users",
  vacancyExcludedWords: "/api/admin/vacancy-excluded-words",
  blogArticles: "/api/blog/articles",
  blogImages: "/api/blog/articles/images",
} as const;
